### ISSUE TITLE
INFO: About windows glitch that prevents kcdshop to open vs-code

### ISSUE THREAD

**Issue by onemen** [epicweb-dev/kcdshop#10]
![not-open](https://user-images.githubusercontent.com/3650909/226105102-b786ca49-6916-4625-9b84-04ff6336f1b0.png)

**NOTICE:** 
this is not kcdshop error

Reinstalling vs code solve this issue. [vs code update page](https://code.visualstudio.com/updates/)

**Comment by onemen** [comment]
It happened again....

**Comment by kentcdodds** [comment]
What happens if you add `shell: true` next to the `stdio: 'inherit'` option?

**Comment by onemen** [comment]
did not help, i tried all this options
```
{
  stdio: 'inherit',
  shell: true,
  windowsHide: true,
 windowsVerbatimArguments: true,
}
```
all i get is `Command failed with exit code 1`

**Comment by kentcdodds** [comment]
Do you think you could try to switch this to `execa`? Maybe that would fix the issues?

**Comment by onemen** [comment]
I've tried child_process.exec

It failed with very informative error message from windows `Error: Command failed`

this code works from windows cmd terminal but failed from the app
`"C:\\Program Files\\Microsoft VS Code\\Code.exe" -g "C:\\projects\\kcd-apps\\kcdshop\\packages\\example\\exercises\\01.nested-routing\\01-02.problem\\package.json:1:0"`

**Comment by onemen** [comment]
can we use this work around for windows
if the editor path ends with `Code.exe` replace it with `bin\code.cmd`
if the editor path ends with `Code - Insiders.exe` replace it with `bin\code-insiders.cmd`

**Comment by kentcdodds** [comment]
I think the newly supported `.env` thing should satisfy this. Thanks!
