### ISSUE TITLE
`--no-restart` flag is deprecated usee `--manual` instead

### ISSUE THREAD

**Issue by onemen** [epicweb-dev/kcdshop#108]
This should be updated all over epicweb-dev.

https://remix.run/docs/en/1.19.0/guides/manual-mode

https://remix.run/docs/en/1.19.0/guides/manual-mode#keeping-in-memory-server-state-across-rebuilds

is there anything other then Prismae to `remember` ?

**Comment by kentcdodds** [comment]
Yep, we need to get that updated everywhere.

We're currently using something similar we call `singleton`. I personally like that better than `remember`.

**Comment by onemen** [comment]
so we just need to replace --no-restart with --manual
