### ISSUE TITLE
MDX Component: <DiffLink />

### ISSUE THREAD

**Issue by kentcdodds** [epicweb-dev/kcdshop#109]
Sometimes I have 🧝‍♂️ Kellie the Co-worker do a little work between the previous exercise's solution and the current exercise's problem. I'd like to have a component that creates a link.

I can definitely copy a the link and just use that, but it looks like this: http://localhost:5639/02/01/problem?preview=diff&app1=exercises__sep__02.seed__sep__01.solution.init&app2=exercises__sep__02.seed__sep__02.problem.realistic

And that can change relatively easily (if I ever change the directory name). I'd like something a little more future-proof.

I think I'd like the `<DiffLink app1={-1} app2={0} />` which would be "previous app vs current app"

And I'd also like support for something like: `<DiffLink app1="02/01.solution" app2="02/02.problem" />` which would be "exercise 2, step 1 solution vs exercise 2 step 2 problem"

So it's just a shortcut.

**Comment by onemen** [comment]
I can work on it.

Is it a link to diff tab, or you want the diff to appear in the readme?

**Comment by kentcdodds** [comment]
Good question... Let's have it link to the diff tab.

**Comment by kentcdodds** [comment]
Thanks!

**Comment by kentcdodds** [comment]
This can now link to the `/diff` route and I think that's what I'd prefer to do.
