### ISSUE TITLE
Make "Set to Playground" faster

### ISSUE THREAD

**Issue by kentcdodds** [epicweb-dev/kcdshop#110]
Sometimes it takes *very* long. Some ideas:

1. Stop the server, do the set to playground, start the server. This would reduce issues with #93
2. Delete the entire playground and copy the entire exercise. If I remember right we override existing files then delete the extra ones right now...

**Comment by onemen** [comment]
- make playground a git submodule
- generate on setup one commit for each step problem

now you can use git checkout `01.styling-01.problem.public-links` as `Set to Playground` command

**Comment by kentcdodds** [comment]
I've used git submodules before years ago and it was very painful. But I'll explore this idea... Can I do this even if the playground directory is in the `.gitignore`?

**Comment by onemen** [comment]
i think it is possible.

but we can simplify every this if we move the `playground` out of the workshop folder and place it as a sibling folder

 workshop
  |- full-stack-foundations
  |- playground

**Comment by kentcdodds** [comment]
That wouldn't work very well due to shared dependencies in `node_modules`. The playground needs to resolve dependencies in `full-stack-foundations/node_modules` and therefore has to be under that directory.

**Comment by kentcdodds** [comment]
Ok, so I just tried changing it so we're less smart about which files we delete:

```diff
diff --git a/packages/workshop-app/utils/apps.server.ts b/packages/workshop-app/utils/apps.server.ts
index 9b96489..62064e8 100644
--- a/packages/workshop-app/utils/apps.server.ts
+++ b/packages/workshop-app/utils/apps.server.ts
@@ -922,7 +922,6 @@ export function getAppPageRoute(app: ExerciseStepApp) {
 }
 
 export async function setPlayground(srcDir: string) {
-	const isIgnored = await isGitIgnored({ cwd: srcDir })
 	const destDir = path.join(getWorkshopRoot(), 'playground')
 	const playgroundFiles = path.join(destDir, '**')
 	getOptionalWatcher()?.unwatch(playgroundFiles)
@@ -934,51 +933,14 @@ export async function setPlayground(srcDir: string) {
 		await closeProcess(playgroundApp.name)
 	}
 
-	const basename = path.basename(srcDir)
-	// If we don't delete the destination node_modules first then copying the new
-	// node_modules has issues.
-	await fsExtra.remove(path.join(destDir, 'node_modules'))
+	console.time('setPlayground')
+	await fsExtra.remove(destDir)
 	// Copy the contents of the source directory to the destination directory recursively
 	await fsExtra.copy(srcDir, destDir, {
 		overwrite: true,
 		preserveTimestamps: true,
-		filter: async file => {
-			if (
-				file.includes(`${basename}${path.sep}build`) ||
-				file.includes(`${basename}${path.sep}public${path.sep}build`)
-			) {
-				return false
-			}
-			if (file === srcDir) return true
-			// we copy node_modules even though it's .gitignored
-			if (file.includes('node_modules')) return true
-			// make sure .env is copied whether it's .gitignored or not
-			if (file.endsWith('.env')) return true
-			const shouldCopy = !isIgnored(file)
-			return shouldCopy
-		},
 	})
-
-	async function getFiles(dir: string) {
-		// make globby friendly to windows
-		const dirPath = dir.replace(/\\/g, '/')
-		const files = await globby([`${dirPath}/**/*`, '!**/build/**/*'], {
-			onlyFiles: false,
-			dot: true,
-		})
-		return files.map(f => f.replace(dirPath, ''))
-	}
-
-	// Remove files from destDir that were in destDir before but are not in srcDir
-	const srcFiles = await getFiles(srcDir)
-	const destFiles = await getFiles(destDir)
-	const filesToDelete = destFiles.filter(
-		fileName => !srcFiles.includes(fileName),
-	)
-
-	for (const fileToDelete of filesToDelete) {
-		await fsExtra.remove(path.join(destDir, fileToDelete))
-	}
+	console.timeEnd('setPlayground')
 
 	const appName = getAppName(srcDir)
 	await fsExtra.ensureDir(path.dirname(playgroundAppNameInfoPath))

```

I thought it would be better, but it was *way* worse 😆 Like it went from ~300ms to update the playground with a big change to like several seconds 🙃

And we *already* stop and start the server like I thought. So both of my ideas are no good 😅

**Comment by onemen** [comment]
regarding prepareForDiff, why you need to copy all the files to a temp folder before calling 'diff'

isn't it possible to call git on the step folder directly ?

**Comment by kentcdodds** [comment]
The reason we copy it to a temp directory and diff there is because there are some files we don't want in the diff. If we could figure out how to remove those from the parsed diff though then maybe that would be more efficient!

**Comment by onemen** [comment]
how about using `:(exclude)` pathspec. [git docs](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-exclude)

we can always filter diffOutput result we get from `git diff`

**Comment by kentcdodds** [comment]
Oh man, I didn't know about that feature. I'm definitely open to trying that out.

**Comment by onemen** [comment]
:exclude is not available when using `git diff` with '--no-index',

I can use `git diff --no-index` to get changes, filter the output to exclude unused files and use `git apply` to apply the changes to the playground.  

we can manually copy other files like data.db

anyhow the problem here is not the copy time 200-300ms is fast.
stopping and starting the app take most of the time, more than 6 seconds.

maybe you just don't stop the playground and only restart it if it crash when applying set-playground

**Comment by kentcdodds** [comment]
Oh, haha, now I remember. I did try that, but bumped into the same issue 😅

> anyhow the problem here is not the copy time 200-300ms is fast. stopping and starting the app take most of the time, more than 6 seconds.
> 
> maybe you just don't stop the playground and only restart it if it crash when applying set-playground

Ah, that's interesting! Yes, let's try that first!

**Comment by kentcdodds** [comment]
Ok, so I'm trying this out and my biggest concern is Remix's file watcher is going to become overwhelmed with the changes. I also noticed that the user has to hit "refresh" on the in-browser browser to get the iframe updated. I tried using a `key` prop to get the iframe re-mounted after the playground is updated and this worked ok, but sometimes the app isn't *quite* ready with the `public/build` output, so I get 404s on those. I've tried adding a delay, but interestingly I'm ...

Ok, actually I just figured out how to deal with the refresh issue, and I don't even need a delay!

I have an idea for how to avoid overwhelming the remix file watcher, but it only works on macOS and Linux (maybe WSL too?). I'm going to investigate this more.

**Comment by kentcdodds** [comment]
Ok, this should make it much faster: https://github.com/epicweb-dev/kcdshop/commit/a1cb79c1a054cd48826419baff7e4698ef2c19c7

Thanks for the idea of not stopping and starting the server if it's unnecessary. I think the reason I did this originally was because I was concerned about the Remix Dev Server being overwhelmed by the number of file changes. But I tested it by switching back and forth on the first and last exercises of web forms and it seemed to work ok for that.

I think it would be a good idea to address this though. So I'm going to leave this open.

**Comment by onemen** [comment]
You can add some flag when set-playground is running to skip reloadin build/index.js from the server watcher. Then when set-playground finish. import build/index.js and notify remix

**Comment by kentcdodds** [comment]
I'm not sure I follow what you mean. Do you mean this code change would have to happen in the exercise apps or is this something we could do from within the workshop app?

**Comment by onemen** [comment]
I did not test it.
I meant to try to do it on the exercuse app server/index.js

**Comment by onemen** [comment]
every time i click set playground when the playground running i get this error on data-modeling.
but the file 'C:\projects\kcd-apps\data-modeling\playground\build\index.js' exist.
i have to stop the up and start it again

```shell
[playground:4000] Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\projects\kcd-apps\data-modeling\playground\build\index.js' imported from C:\projects\kcd-apps\data-modeling\playground\server\index.ts
[playground:4000]     at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
[playground:4000]     at new NodeError (node:internal/errors:405:5)
[playground:4000]     at finalizeResolution (node:internal/modules/esm/resolve:324:11)
[playground:4000]     at moduleResolve (node:internal/modules/esm/resolve:943:10)
[playground:4000]     at defaultResolve (node:internal/modules/esm/resolve:1129:11)
[playground:4000]     at nextResolve (node:internal/modules/esm/loader:163:28)
[playground:4000]     at u (file:///C:/projects/kcd-apps/data-modeling/node_modules/@esbuild-kit/esm-loader/dist/index.js:1:2406)
[playground:4000]     at async nextResolve (node:internal/modules/esm/loader:163:22)
[playground:4000]     at async ESMLoader.resolve (node:internal/modules/esm/loader:835:24)
[playground:4000]     at async ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:7)
[playground:4000]     at async ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:21) {
[playground:4000]   code: 'ERR_MODULE_NOT_FOUND'
[playground:4000] }
```

**Comment by onemen** [comment]
a workaround to this issue is to use something like this code in the workshop apps server/index.ts

```diff
-// @ts-ignore - this file may not exist if you haven't built yet, but it will
-// definitely exist by the time the dev or prod server actually runs.
-import * as remixBuild from '../build/index.js'
const MODE = process.env.NODE_ENV

const BUILD_PATH = '../build/index.js'

-const build = remixBuild as unknown as ServerBuild
+let buildPromise: Promise<ServerBuild> | null = null

+const getBuild = async (): Promise<ServerBuild> => {
+  if (buildPromise) {
+    return buildPromise
+  }
+
+  try {
+    return await import(`${BUILD_PATH}?update=${Date.now()}`)
+  } catch (error: any) {
+    if ('code' in error && error.code === 'ERR_MODULE_NOT_FOUND') {
+      buildPromise = new Promise(resolve => {
+        setTimeout(() => {
+          resolve(getBuild())
+        }, 100)
+      })
+      return buildPromise
+    } else {
+      throw error
+    }
+  } finally {
+    buildPromise = null
+  }
+}

+const build = await getBuild()
let devBuild = build
```

**Comment by onemen** [comment]
maybe you can export a promise from `apps.server.ts`, that is default to resolved state, and will be set to pending while setPlayground is runnnig, when the workshop tsx watcher calls server/index.js we can use dynamic import (with time stamp) to import the `setPlaygroundPromise` and wait to its resolved before importing build/index.js

**Comment by kentcdodds** [comment]
I really want to try and avoid the exercise apps knowing anything about the fact that they're running within the workshop app.

**Comment by onemen** [comment]
using the workaround above work.

**Comment by onemen** [comment]
another related issue i have while working on `data-modeling`

when clicking `Set plyground` while the app is running:
![prisma_error](https://github.com/epicweb-dev/kcdshop/assets/3650909/44fac55f-8d77-400a-85d4-2acf87bb0bfd)

i think this is triggered in `fixup-playground.js`, i did not see any log regarding this error in the terminal.
in other cases there was a message that data.db is busy

maybe you need to run `prisma.$disconnect()` before `setPlayground` delete/copy files, you can call this script `fixdown-playground.js`

**Comment by onemen** [comment]
it look like that in some workshops, `data-modeling` for example ,you must stop running playground app before updating it

i think it is safe to do set-playground without stopping the app only on workshops where exercise node_modules is is empty

**Comment by kentcdodds** [comment]
I think we've done as much as we can on this. It's actually pretty efficient now.
