### ISSUE TITLE
The address bar somehow appears above the scrollbar when stacked vertically 🤷‍♂️

### ISSUE THREAD

**Issue by kentcdodds** [epicweb-dev/kcdshop#112]
<img width="526" alt="image" src="https://github.com/epicweb-dev/kcdshop/assets/1500684/493399f7-c9e1-4c36-88ac-b183657e0c04">

**Comment by onemen** [comment]
https://github.com/epicweb-dev/kcdshop/blob/a3722a5aaa40f14e92c4980ac1967283ea9f40ba/packages/workshop-app/app/routes/_app%2B/_exercises%2B/%24exerciseNumber_.%24stepNumber.%24type.tsx#L651-L655

its the z-index: 10 that was added to `Tabs.Content` wrapper, the scroll bar is from the `Tabs.List`

option 1: add `z-20` to Tabs.List className
option 2: remove `z-10` from `Tabs.Content` wrapper.
option 2: change `z-10` on `Tabs.Content` wrapper to `lg:z-10` 

@vojtaholik, can you check if `z-10` is needed ?

**Comment by kentcdodds** [comment]
Let's go ahead and remove it and maybe we'll find out why it was removed to begin with 😅

**Comment by kentcdodds** [comment]
Actually, let's re-evaluate...

Part of the problem is the scrollbar itself. I have it going over the content below because if I don't then there's a gap for the scrollbar which looks funny. If we can somehow make the scrollbar only create the gap when it appears then I think I'd prefer that.

**Comment by onemen** [comment]
i think that it is better here without scrollbar. just reduce the font size on small screen to 12px and hide the scroll bar

**Comment by kentcdodds** [comment]
I agree it looks better without the scrollbar, but we do need to scroll if the screen is very narrow.

**Comment by onemen** [comment]
just add `z-20` to Tabs.List className, i don't see any issue with it

**Comment by kentcdodds** [comment]
Sounds good to me 👍
