### ISSUE TITLE
Make diff lines show line number on hover

### ISSUE THREAD

**Issue by kentcdodds** [epicweb-dev/kcdshop#115]
These can get rather long and it could be handy to display the line number when the user hovers over that area:

<img width="133" alt="image" src="https://github.com/epicweb-dev/kcdshop/assets/1500684/a8df53fa-dc45-46eb-bc03-e071eed84211">

To be clear, not on hover of the line (that would be annoying), but if the user hovers the `+` or `-` it should switch to the line number it represents.

**Comment by onemen** [comment]
![diff](https://github.com/epicweb-dev/kcdshop/assets/3650909/f877f1f7-f224-4cf2-b22d-e9d23459ef78)

do you think we can do github diff?

**Comment by kentcdodds** [comment]
I think that takes up too much space. The line numbers aren't important enough to take up that much space.

**Comment by onemen** [comment]
> To be clear, not on hover of the line (that would be annoying), but if the user hovers the `+` or `-` it should switch to the line number it represents.

it is not possible to apply a :hover pseudo-class directly to a :before or :after pseudo-element.

**Comment by kentcdodds** [comment]
Ah, I worried about that. Oh well. Not worth the complexity or effort then.
