### ISSUE TITLE
Add notice on deployed version

### ISSUE THREAD

**Issue by kentcdodds** [epicweb-dev/kcdshop#118]
On at least the home page (but probably on every page), we should have a notice that explains the deployed version is limited. For two reasons:

1. I don't want people getting the wrong impression about what it's like to go through a workshop with me.
2. I want people to understand why they can't start apps like they can when it's local.

**Comment by onemen** [comment]
I don't quite understand, what is the purpose of the deployed version.

who is going to use "deployed version" instead of cloning the workshop?

![deployed](https://github.com/epicweb-dev/kcdshop/assets/3650909/f6f001a3-fb47-431b-b648-1e6f4ec7e57e)

add this to root.tsx:
```tsx
{ENV.KCDSHOP_DEPLOYED ? (
	<div>
		<h6 className="border-b border-border p-2 font-mono text-sm font-medium uppercase leading-tight">
			Limited deployed version
		</h6>
		<Outlet />
	</div>
) : (
	<Outlet />
)}
```

you can replace the `<h6>`  with a link to a README page with more details. also add menu entry to that README to the sidebar below `Workshop Feedback`

I can make a PR if you provide the content of the README and where to save it

**Comment by kentcdodds** [comment]
People will use the deployed version as a quick and easy way to reference the material without having to run things locally. I do this all the time myself and I expect folks who have gone through it in the past will as well.

**Comment by kentcdodds** [comment]
The example you have there, will that force a scroll on the page or do things adjust to fit it? I think that looks ok.

**Comment by onemen** [comment]
> The example you have there, will that force a scroll on the page or do things adjust to fit it? I think that looks ok.

Yes. currently there is an extra scroll, since the `Outlet` page have h-full or h-screen, what will be the simplest way to fix it?

where can i find a deployed versions of the workshops ?

**Comment by kentcdodds** [comment]
https://epicweb-dev-full-stack-foundations.fly.dev/
https://epicweb-dev-web-forms.fly.dev/
https://epicweb-dev-data-modeling.fly.dev/

They're linked in the repo readme.

**Comment by kentcdodds** [comment]
We'll want to avoid the scroll

**Comment by onemen** [comment]
I found a solution for the scroll issue by adding custom classes to tailwind.config:

```
height: {
	'screen-custom': KCDSHOP_DEPLOYED ? 'calc(100vh - 2.5rem)' : '100vh',
	'full-custom': KCDSHOP_DEPLOYED ? 'calc(100% - 2.5rem)' : '100%',
},
```

and use h-screen-custom and h-full-custom in `_app+` routes

do you want to add a doc file with a link in the side bar?

> They're linked in the repo readme.

I did not find these link

**Comment by kentcdodds** [comment]
They're linked on this image in each of them

![image](https://github.com/epicweb-dev/kcdshop/assets/1500684/ce6ef653-2de4-4e5e-ad67-9f7a39c5303d)

I'd rather a solution that doesn't require customizing the tailwind config
