### ISSUE TITLE
Fix scrolling on /diff view

### ISSUE THREAD

**Issue by kentcdodds** [epicweb-dev/kcdshop#129]
When the diffs are long enough to go past the bottom of the screen, a scrollbar shows up on the right for the whole window and the nav buttons on the bottom are squished.

<img width="218" alt="image" src="https://github.com/epicweb-dev/kcdshop/assets/1500684/c41150f0-2be4-4cbf-9d81-afac9031eb11">

**Comment by onemen** [comment]
![diff-scroll-issue](https://github.com/epicweb-dev/kcdshop/assets/3650909/7c906de4-1887-4e85-a430-91caa8d00c70)

is it on deployed app?
is it on narrow screen?
where do you see the view with buttons bellow the diff?
can you post complete screenshot ?

**Comment by kentcdodds** [comment]
This is on the `/diff` route. It happens on both deployed and local. It only happens when the diff content is taller than the viewport.

Here's the `/diff` for the local data-modeling workshop:

<img width="1200" alt="image" src="https://github.com/epicweb-dev/kcdshop/assets/1500684/bde2cb3a-9ed3-48fd-bcbd-726fc4b32229">

**Comment by kentcdodds** [comment]
It's not a problem if the view is tall enough:

<img width="1351" alt="image" src="https://github.com/epicweb-dev/kcdshop/assets/1500684/057b9be7-f5d3-4c09-80bf-391787eabbaa">

**Comment by onemen** [comment]
OK,

I probably did not test diff route when working on #121

i will work on it now

are there any other route with different layout?

**Comment by kentcdodds** [comment]
There's the `/admin` route, but that one's not very important currently.
