### ISSUE TITLE
can not login to any non intro video

### ISSUE THREAD

**Issue by onemen** [epicweb-dev/kcdshop#147]
Setting `KCDSHOP_CONTEXT_CWD` to latest `full-stack-foundations` all videos other then intro videos shows login message

![login](https://github.com/epicweb-dev/kcdshop/assets/3650909/d722eb7f-3b68-4159-be6e-47193d0ea764)

in `https://www.epicweb.dev/workshops/full-stack-foundations` i can watch all videos

**Comment by kentcdodds** [comment]
Going to be changing this in a big way later today on stream. I'll be rendering the Mux player directly instead of an iframe
