### ISSUE TITLE
Typo on EpicWeb Landing Page

### ISSUE THREAD

**Issue by adhanji8** [epicweb-dev/kcdshop#154]
Hey Kent,
Sorry, I wasn't sure where to mention this, just a small typo on the landing page for epicweb:
Under Web Authentication:
"Password Validation: Security **that** without inconvenience."

Expected: Maybe "Security without inconvenience" or "Security that's without inconvenience"

Hyped for the launch! :) 

<img width="918" alt="image" src="https://github.com/epicweb-dev/kcdshop/assets/55081439/52d713d1-b8fd-4d10-a9cc-76f3f52aa44b">

**Comment by kentcdodds** [comment]
I'll let the team know!
