### ISSUE TITLE
Concerns w/ PartyKit

### ISSUE THREAD

**Issue by sadikaya** [epicweb-dev/kcdshop#163]
When you start the workshop app and have it connected it to EpicWeb, the default behaviour is that presence is enabled and it's broadcasting your full name to everyone. If connecting to Discord, it then changes the full name to the Discord username.

I would argue that this should be something users consent to and decide they should decide if they want to opt-in.

**Comment by kentcdodds** [comment]
Thanks for voicing your concern.

When you sign up for EpicWeb.dev, you're joining a community (much like Discord), not learning in a vacuum. I understand not everyone wants their presence to be known which is why I allow for opt-out, but the community aspect is a very important part of the workshops, so we're going to keep it as an opt-out.

Thanks!

**Comment by sadikaya** [comment]
I understand the sentiment, but it's not mentioned in the privacy policy that user information is shared with PartyKit.

It is mentioned in the terms and conditions under section 7 that you might provide third-party tools, and that users should make themselfes familiar with and approve these third-party terms. But it is not obvious that this is happening, it's not even obvious that our data is now being processed by PartyKit while running a local instance of the workshop app.

Also, the material on EpicWeb does not state anywhere that users are signing up for a community, in fact, the only text I could find is the following, "You'll also be invited to join the Epic Web community, where you can ask questions, share your progress, and even find a cohort to work through the workshop with." Which I read as users gets to decide if they want to be part of the community or not.
