### ISSUE TITLE
Not possible to control Video Speed Playback from Chrome Extensions

### ISSUE THREAD

**Issue by thomasfr** [epicweb-dev/kcdshop#172]
Hi,
i am using Video Speed Controller Chrome Extension (https://github.com/igrigorik/videospeed) but its not working on the Workshop App. I like to use my keyboard to quickly increase and decrease the speed in smaller steps and also to jump back and forth a few seconds without using my mouse.
The Chrome extension has permissions to work locally

**Comment by kentcdodds** [comment]
I'm afraid you'll need to reach out in the extension to see what they can do to support the Mux player because I don't have the bandwidth to fix issues with third party extensions.

**Comment by thomasfr** [comment]
Thanks, will do. Here is the tracking issue: https://github.com/igrigorik/videospeed/issues/1072

**Comment by kentcdodds** [comment]
Thank you! I hope it gets fixed soon!
