### ISSUE TITLE
Playground mode has no code formatting

### ISSUE THREAD

**Issue by kettanaito** [epicweb-dev/kcdshop#183]
## The problem

This is a problem similar to #182. Since the `playground` directory doesn't have any `.prettierrc`, the student going through the exercise will end up in either of two states:

1. No code auto-formatting. This can make them struggle while typing and will also result in distorted "Diff" once viewed in the App's UI.
2. Their _default_ auto-formatting. Only the Git diff will be distorted, preventing them from finding actual _logical_ difference in the diff.

## The solution

- We can symlink `.prettierrc` from the root-level as well. 
- If we choose not to symlink the config, we should at least format both "ours" and "theirs" parts of the diff using the same Prettier config so to have a proper diff (this may visually modify the student's solution though so be careful about this).

**Comment by kentcdodds** [comment]
Hmmmm.... I would recommend configuring prettier via the package.json or a `.prettierrc` within the exercise folders (next to the package.json).

I don't think the workshop app should do anything about this specifically. Alternatively a solution similar to what I suggested in #182 could work for this as well.

**Comment by kettanaito** [comment]
@kentcdodds, a great point. Will do! Thanks.
