### ISSUE TITLE
Allow custom feedback forms

### ISSUE THREAD

**Issue by kettanaito** [epicweb-dev/kcdshop#185]
## The problem

The feedback Google forms after each exercise and after the entire workshop are hard-coded at the moment. This makes it difficult for other instructors at EpicWeb.dev to tailor a personalized experience for their workshops. 

> The form at the end of the workshop also greets the reader from Kent's name and mentions how to find him on Twitter.

## The solution

Support custom `feedbackFormLink` property on the workshop. 

### Exercise-level feedback forms

```
exercises/
  01.foo/
    01.bar.problem/
    01.bar.solution/
    package.json
```

```
// exercises/01.foo/package.json
{
  "feedbackFormUrl": "https://..."
}
```

### Workshop-level feedback forms

```
// ./package/json
{
  "feedbackFormUrl": "https://..."
}
```

**Comment by kentcdodds** [comment]
This sounds reasonable to me, though I wouldn't do a package.json, I'd probably do a config.json or something. I'll give this more thought.

For now, I'll update the feedback form to not mention myself.

**Comment by kettanaito** [comment]
I believe this is supported now via: 

https://github.com/epicweb-dev/kcdshop/blob/de8e6a41db61a2c7bd872dec5dc801bc8dad3efb/docs/other.md#forms

Nice!
