### ISSUE TITLE
Diff is visible even on the "problem" state of the exercise

### ISSUE THREAD

**Issue by kettanaito** [epicweb-dev/kcdshop#186]
This might be a bug I caught but when I was going through my workshop, when I landed on a "problem" part of the exercise, I could see the diff for the _solution_ if I clicked on the "Diff" tab in the App's UI. 

Is this intentional for those who want hints? If not, this may be a bug.

**Comment by kentcdodds** [comment]
This is definitely intentional for those who want hints if they get stuck
