### ISSUE TITLE
Git creates an ".swp" file for a JavaScript module

### ISSUE THREAD

**Issue by kettanaito** [epicweb-dev/kcdshop#187]
This may not be a bug in the App necessarily, but when going through the workshop, I noticed something creating `.swp` files next to my JavaScript modules. So, `foo.js` and `foo.js.swp` next to it. I wasn't doing any Git manipulations myself. I was using the App directly. 

> I had to upgrade my Git _before_ running `npm run setup` of the entire workshop once. I can't imagine that could have caused this but it's something to mention.

**Comment by kentcdodds** [comment]
This is very odd. Are you using vim? Because that is a file that vim creates. There's nothing in the workshop that would create those files.
