### ISSUE TITLE
"Exit full screen" button sometimes doesn't work

### ISSUE THREAD

**Issue by denkasyanov** [epicweb-dev/kcdshop#189]
Sometimes, the "exit full screen" button appears as an "enter full screen" button and doesn't work.

So, I am only able to exit full screen mode with the Escape key.

I haven't noticed a pattern, but experienced it twice on different pages.

<details><summary>Screenshots with both modes</summary>
<p>

![CleanShot 2024-02-04 at 02 06 43@2x](https://github.com/epicweb-dev/kcdshop/assets/34678129/9c89ca0a-cc58-4797-8650-56cc040de5e4)
![CleanShot 2024-02-04 at 02 06 53@2x](https://github.com/epicweb-dev/kcdshop/assets/34678129/e0575d9d-e16a-4e6e-a3dc-c857d0c32962)

See the bottom right corner in the second screenshot

I'm sorry for how perfect I chose a moment to make them 😅
</p>
</details>

**Comment by kentcdodds** [comment]
Hmmm... I'm not sure what could be causing that. I'm using `@mux/mux-player-react@2.3.1` and I'm guessing something's either wrong with [the way I'm using it](https://github.com/epicweb-dev/kcdshop/blob/40d20ec48d899ba257212ffdbb15d5815851ee12/packages/workshop-app/app/routes/video-player/index.tsx) or with that package. cc @cjpillsbury and @luwes have you ever seen something like this before?

**Comment by denkasyanov** [comment]
So the steps that allow me to reproduce it in my environment

- Experience the issue with some video
- Reload the page with Ctrl + R / Ctrl + Shift + R
- Watch video on this page without issues with full screen mode
- Go to another page with another video (using buttons at the bottom of the screen)
- Enter the full screen mode in another video
- The issue is present

Just updated/relaunched Chrome to the latest version and am still able to reproduce it with the steps above.

**Comment by onemen** [comment]
i've just check the video in [MUX Docs](https://docs.mux.com/guides/play-your-videos) and exit fullscreen button doesn't work as well

**Comment by cjpillsbury** [comment]
Hey sorry for the delay @kentcdodds, just caught this. Either myself or @luwes will try to peel away some time to investigate asap, but you may have uncovered a bug! Will keep you posted.

**Comment by kentcdodds** [comment]
Thanks!

**Comment by denkasyanov** [comment]
Looks like it is fixed now.
Thanks!
