### ISSUE TITLE
cliped corner on the buttons is not the same

### ISSUE THREAD

**Issue by onemen** [epicweb-dev/kcdshop#20]
![cliped_buttons](https://user-images.githubusercontent.com/3650909/227156093-e79cbcc8-d248-40a2-a6f1-5ba09e683c0d.png)

```css
.clip-path-button {
	clip-path: polygon(0 0, 100% 0, 100% 75%, 90.5% 100%, 0 100%);
}
```

Hi @kentcdodds,
Its a little bit of cosmetics, but do you we need to unified the cut corner?

To make problem buttons clip in the corner in change this section [navigation layout](https://github.com/epicweb-dev/kcdshop/blob/main/packages/workshop-app/app/routes/_app%2B/_exercises%2B/_layout.tsx#L177-L188) (lines 177-188)

```diff
	<Link
		to={`/${exerciseNum}/${step}`}
		className={clsx(
-			'whitespace-nowrap px-2 py-0.5 pr-3 text-xl font-medium hover:underline',
-			{
-				// TODO: figure out how to make it clip in the corner
-				'bg-black text-white': isActive,
-			},
+			'clip-path-button whitespace-nowrap px-2 py-0.5 pr-3 text-xl font-medium hover:underline',
+			{ 'bg-black text-white': isActive },
		)}
	>
		{step}. {title}
	</Link>
```

**Comment by kentcdodds** [comment]
I just pushed this change. Thank you!
