### ISSUE TITLE
Lighthouse performance score is 80

### ISSUE THREAD

**Issue by onemen** [epicweb-dev/kcdshop#23]
![lighthouse](https://user-images.githubusercontent.com/3650909/227525758-41444faa-48c7-4815-80d2-ec3453a02850.png)

**Comment by kentcdodds** [comment]
I'm not really concerned about improving this number. We're running on-device and it's definitely fast enough 🤷‍♂️

Thanks though! Happy to look at specific suggestions. Especially for any of those accessibility warnings.
