### ISSUE TITLE
TouchedFiles popup show error for a split second

### ISSUE THREAD

**Issue by onemen** [epicweb-dev/kcdshop#26]
I am working on **'Open all Files'**

![open-all-files](https://user-images.githubusercontent.com/3650909/227974995-21fcc1ff-d1a9-454e-ade8-6fe602800138.png)

I have noticed that when the launch editor return an error it only appear in the popup for a split second
![TouchedFiles](https://user-images.githubusercontent.com/3650909/227978994-f73c5978-8f5c-48d0-a95b-d5d0e7459ab0.png)

When clicking on a button in `TouchedFiles' popup,  `LaunchEditor` (launch-editor.tsx) form renders 3 times, with these fetcher values: 
-  state.submitting, `data: undefined`
-  state.loading, 

```
   data: {
	  // i throw an error for testing
	  error: "testing error from launchEditor, with very very very long error message"
	  status: "error"
  }
```

-  state.idle, `data: undefined`

1. I don't know what triggers the 3rd fetcher, but it clear the error
2. do you want to change how the error looks in the popup? width. color, duration?
3. since each `InlineFile` have its own form when one form is submitting in `TouchedFiles` all other forms in the popup rendering 3 times each, not only the one that was clicked

**Comment by onemen** [comment]
many time after using `TouchedFiles` popup, i see this message:
```
:5639/02/01/problem:1 
The resource http://localhost:5639/neogrotesk-font.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

**Comment by onemen** [comment]
## renders

Everything is renders multiple times when clicking on button in TouchedFiles list
![render](https://user-images.githubusercontent.com/3650909/228032643-0b9bee53-9e73-446e-b6de-6acd048434b2.png)

**Comment by onemen** [comment]
https://user-images.githubusercontent.com/3650909/228039833-b85a5cbc-4ba4-48b5-9955-fde525abf911.mp4

**Comment by kentcdodds** [comment]
Thanks for working on this!

1. I don't mind that it's rerendering a bunch of stuff. It's not causing any issues that I can tell.
2. I would like the error to remain until the fetcher is re-triggered
3. Let's make sure that "Open All Files" only triggers a single fetcher and the server-side code just handles opening all the files provided.
4. Let's style the error in red. We really should implement some kind of "toast" message thing so we can display the error outside that box for situations like this.

**Comment by onemen** [comment]
How about, I open a PR with what I have so far, but it is still a work in progress?

> 1. I don't mind that it's rerendering a bunch of stuff. It's not causing any issues that I can tell.

maybe you can handle is in a future optimization...

> 2. I would like the error to remain until the fetcher is re-triggered

I would like that to, how can I know if the fetcher is in state.idle for the first render or it is in state.idle after loading was finished, I will try to look how you do it in `rocket rental`. I will appreciate any pointers on this one. 

> 3. Let's make sure that "Open All Files" only triggers a single fetcher and the server-side code just handles opening all the files provided.

I've modified `readme-files-section.server.ts` and `launch-editor.server.ts` to handle multiple files with one fetcher.

```html

from README.mdx

<TouchedFiles>
  <div id="files">
    <ul>
      <li data-state="all-files">
        <InlineFile file="app/entry.server.tsx,app/root.tsx,app/routes/deleted.tsx,app/routes/index.tsx,app/routes/parent.tsx,package.json">
          Open All Files
        </InlineFile>
      </li>

      <li data-state="modified">
        <span>modified</span>

        <InlineFile file="app/entry.server.tsx" />
      </li>
```

> 4. Let's style the error in red. We really should implement some kind of "toast" message thing so we can display the error outside that box for situations like this.

Currently the error message appear below the button that was clicked.
If we instead show it in a separate "toast", where should it be display?,
Another UI question is when to close `TouchedFiles` popup, currently it is stay open after user click on a button to open file/files, but I don't like it.
Do we close TouchedFiles popup after user click, or only when `Open All Files` was click, leave it open on error?
I think it is best to always close the popup after user click on it and show a "toast" it a case of an error. maybe we can modify `TouchedFiles' to show only the error message in that case and stay open?

#### Refactor idea
How about we pull all `TouchedFiles` info from readme files and instead generate a `exercises.json` file with all the static info about the exercises: exercises titles, steps, touched files, diff. it can simplify getApps
Then we can use the data both server-side and client-side, we only need to render `FILES` button server-side, and handle `TouchedFiles` separately, and mot part of the readme MDX, maybe only in client side.

**Comment by kentcdodds** [comment]
> I've modified readme-files-section.server.ts and launch-editor.server.ts to handle multiple files with one fetcher.

I think it would make sense for InlineFile to optionally accept a "files" prop that's an array so we don't worry about splitting the files by a delimiter like `,`.

> popup

I agree it would make the most sense to have the popup close right away and have a toast notification (probably in the bottom right corner) that shows up in the case that we have an error. We could probably borrow the notification implementation from my personal site: https://github.com/kentcdodds/kentcdodds.com/blob/main/app/components/notification-message.tsx

> Refactor Idea

Actually, I'm working on #25 today, and if it works out, then we can probably have the files list be determined at runtime instead of committing them. This should work because if #25 ends up working out people wouldn't be changing code in the `exercises` directory at all. I'll keep you informed.

Thanks!
