### ISSUE TITLE
kcdshop does not handle mergeMeta

### ISSUE THREAD

**Issue by onemen** [epicweb-dev/kcdshop#31]
You did it only in [web-app-fundamentals](https://github.com/epicweb-dev/web-app-fundamentals/commit/a97cc7109da26fbfcd1fe0fa6877e319a9f5a0ff)

Let me know if you want me to copy/paste the same code to a PR

currently all page except the root are missing:
```
    charset: 'utf-8',
    viewport: 'width=device-width,initial-scale=1',
```

**Comment by kentcdodds** [comment]
Yeah, we should probably do that here too

**Comment by onemen** [comment]
This screenshot is from `web-app-fundamentals/exercises/09.accessibility/01.problem.labels/app/routes/users_+/$username.index.tsx`

this is the code
```typescript
export const meta = mergeMeta(({ data, params }) => {
	const displayName = data?.user.name ?? params.username
	return [
		{ title: `${displayName} | Rocket Rental` },
		{
			name: 'description',
			content: `${displayName} on Rocket Rental is not a host or renter yet.`,
		},
	]
})
```

and this is the result

![meta](https://user-images.githubusercontent.com/3650909/229516026-e87aa309-a789-46c2-b4fc-6d543ecf8e5b.png)

look like something is not right with `mergeMeta`

**Comment by kentcdodds** [comment]
Weird. Looks like we should remove the `metaMerge` thing anyway so maybe it's no big deal.

**Comment by onemen** [comment]
I will check how to update `web-app-fundamentals` to work better with the meta.

[Remix V2 docs](https://remix.run/docs/en/dev/route/meta-v2#merging-with-parent-meta), `mergeMeta` [code & example](https://gist.github.com/ryanflorence/ec1849c6d690cfbffcb408ecd633e069).

There is a new `matches` props that we can use...

**Comment by kentcdodds** [comment]
I was unable to reproduce this. But I am going to change that exercise. Thanks!
