### ISSUE TITLE
The resource was preloaded using link preload but not used within a few seconds

### ISSUE THREAD

**Issue by onemen** [epicweb-dev/kcdshop#44]
I see this warning all the time for all the resources loaded from:
```
remix.run resource http://localhost:5639/build/_assets/tailwind-E25BMFDR.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

https://github.com/epicweb-dev/kcdshop/blob/8f1503545f9c2d72f552c2cfaeb179d13fc0ef5e/packages/workshop-app/app/root.tsx#L24-L34

Do we need to add `as="style"`?

or maybe even change for all links
```diff
-		{ rel: 'stylesheet', href: '/neogrotesk-font.css' }
+		{ rel: 'preload', href: '/neogrotesk-font.css', as: 'style' } 
```
this is [relevant mdn](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel/preload)

Remix docs does not mention the `as` value in the examples for stylesheet, it only include `as` value in images examples.

**Comment by kentcdodds** [comment]
When you include a stylesheet you use `rel: 'stylesheet'`. Remix adds the preload link separately for prefetching. During development that stylesheet URL changes constantly and I think that's why this happens. I'm not concerned.
