### ISSUE TITLE
sidebar emoji is out of sync

### ISSUE THREAD

**Issue by onemen** [epicweb-dev/kcdshop#45]
I've noticed that sometimes `app/routes/_app+/_exercises+/_layout.tsx` runs before `/set-playground` action end.
In this cases playground emoji is out of sync.

I've tried to add `shouldRevalidate` in `app/routes/_app+/_exercises+/_layout.tsx` but it didn't helped, it appear that it is also triggered before the action ends 

I did not find any reference in Remix to a way to asynchronous trigger loader after action from other route completed

_Originally posted by @onemen in https://github.com/epicweb-dev/kcdshop/issues/36#issuecomment-1512595859_

**Comment by onemen** [comment]
1. maybe we need to remove `Cache-Control': 'public, max-age=300' ?

https://github.com/epicweb-dev/kcdshop/blob/8f1503545f9c2d72f552c2cfaeb179d13fc0ef5e/packages/workshop-app/app/routes/_app%2B/_exercises%2B/_layout.tsx#L47-L51

2. how about adding rotated emoji when the playground is on another exercise?
![emoji](https://user-images.githubusercontent.com/3650909/233624703-2c32afb7-e006-4c7a-8d9a-d2ce7114ba2c.png)

**Comment by kentcdodds** [comment]
I'm pretty sure it's the cache header. We can probably remove it, or reduce it to 1 or something if removing it breaks prefetching (though it should not).

I'm fine adding the emoji, but i don't think it makes sense to be sideways.
