### ISSUE TITLE
files watcher slow down set-playground

### ISSUE THREAD

**Issue by onemen** [epicweb-dev/kcdshop#46]
@kentcdodds 

Currently there are multiple file watcher for the entire `packages/example`. 

During the process of coping exercise files to playground, file watcher triggers multiple activities that slow down set-playground significantly.

In my testing, removing `playground` folder from the watcher improve set-playground time by 30-40% for the small example apps included in kcdshop. It can be more meaningful for larger apps included in the workshop.

Maybe kcdshop doesn't need to watch for changes in playground files at all?

`set-playground` already call `getApps` with `forceFresh` to update the cache, the only other place that need update when files change in the playground are diff tab in `getForceFreshForDiff`. for that case when getForceFreshForDiff called with playground as one of the apps, we can check the modified time of the playground directly and update the cache if we need to.

maybe you don't need to watch example files at all during workshop and only update cache for diff?.

**Comment by kentcdodds** [comment]
We need to keep the watcher on the playground for the diff check to be cached efficiently. But we could turn the watcher off and then on again when changing the playground.
