### ISSUE TITLE
globby with `\` return empty list

### ISSUE THREAD

**Issue by onemen** [epicweb-dev/kcdshop#49]
when I was testing `setPlayground` i've noticed that the lists `srcFiles`, `destFiles` and `filesToDelete` are always empty.

I was able to get a result only when I replaced all `\` with `/` for the path that was passed to globby.

how ever i've noticed that if the current app in the playground was running the filesToDelete contains all the files in:
`/build`, `/public` and `/node_modules/.cache/remix` folders.
is it the desire result?

**Comment by kentcdodds** [comment]
Actually I can't remember. Originally I wanted to leave them there just in case those things didn't change, but now I feel like I changed from that because there was an issue. If you remove that behavior does it break anything or make things better?

**Comment by onemen** [comment]
Currently i can't run any of the `rocket rental` [#8](https://github.com/epicweb-dev/rocket-rental/issues/8) and any of the exercises apps in the workshops. I don't think i can get an educated conclusion from the small examples app in `kcdshop`.

As I understand the situation, when playground app is running we have two separate servers.
- kcdshop at post 5639
- playground at post 4000

It look like kcdshop finish to copy and delete files in the playground folder before playground server `Rebuild` triggers.
but I don't know how to make sure this is always the case, what if two consecutive exercise vary in many files?

**Comment by onemen** [comment]
I think we don't need to copy or delete build folder to the playground.
copy new/changed files will trigger a ' Rebuild' PR coming soon...
