### ISSUE TITLE
Ignore .test.ts files in simple apps

### ISSUE THREAD

**Issue by kentcdodds** [epicweb-dev/kcdshop#62]
For simple use cases like the React Advanced Patterns workshop, we need to avoid the test files being used in the diff and the list of changed files.

<img width="304" alt="image" src="https://github.com/epicweb-dev/kcdshop/assets/1500684/cafec6a2-c844-40f4-8f55-b353ba7802f5">

![image](https://github.com/epicweb-dev/kcdshop/assets/1500684/658eb2d3-b74c-4f26-8b55-e8d70c06ec34)

**Comment by onemen** [comment]
it there a way to now when an app is `simple` or the whole workshop is `simple` ?

**Comment by kentcdodds** [comment]
If the `app.dev.type === 'browser'` then it's simple (same for `app.test.type === 'browser'`).

**Comment by onemen** [comment]
I will try tomorrow to add a filter to diff tab and the list of changed files based on app type.
