### ISSUE TITLE
clear outdated file from .cache/compile-mdx

### ISSUE THREAD

**Issue by onemen** [epicweb-dev/kcdshop#80]
@kentcdodds 

while working on #76 ,i have noticed that currently `compileMdx` function (`compile-mdx.server.ts`) create new file when an mdx file change but it never remove old files.

this is not a "big" issue, however my `kcdshop/packages/example/node_modules/.cache/compile-mdx` folder already have more then 500 files.

do you think it worth it to add code to remove outdated file to `compileMdx`, or we just need to remember to clear .cache every now and then.

I can work on it if you want

**Comment by kentcdodds** [comment]
I think we could start deleting things oldest first once we hit 100+

**Comment by onemen** [comment]
how about changing the name format?
instead of  `${md5(`${file}-${stat.mtimeMs}`)}.json`
use
`${md5(file)}-${stat.mtimeMs}.json` the result will be `1bc61ccdbbcf4f037757758f84d4652e-1688934375712.json`
in this format when you create new save for `md5(file) = 1bc61ccdbbcf4f037757758f84d4652e` you can search for all other file starting with same hash and remove them

**Comment by kentcdodds** [comment]
That sounds like a fine idea to me 👍

**Comment by onemen** [comment]
how about we keep the same file and save the timestamp in the file. that also help me in #76. otherwise i have to create another file to keep the info about `codefile` component in the Readme.mdx

**Comment by kentcdodds** [comment]
Oh, yeah, that sounds good to me 👍

**Comment by onemen** [comment]
OK

I will do this change in #76
