### ISSUE TITLE
Handle copying node_modules to playground better

### ISSUE THREAD

**Issue by kentcdodds** [epicweb-dev/kcdshop#81]
I'm pretty sure it would be best if we have a special branch of the code that just deletes the old `node_modules` directory completely and copies the new one over.

I'm not even sure that this would work, but issues like https://github.com/epicweb-dev/full-stack-foundations/issues/2 are really frustrating. It pretty much requires that we make sure everything gets hoisted which can be tricky sometimes.

**Comment by onemen** [comment]
@kentcdodds.

if all `exercises` have the same dependencies you don't need to copy node_modules for each exercise/step just copy it on setup

**Comment by kentcdodds** [comment]
True, but I don't think we can/should count on that. It's possible in the future a workshop will have a step like "now install this dependency" so I think it's reasonable to assume that dependencies could change between exercises.

**Comment by onemen** [comment]
you can use a script before setup start to install all dependencies to make complete list off all dependencies, (dependency from "now install this dependency" should be in the solution of this step any how). then modify `package.json` at the root of the workshop to include al the dependencies, with that setup all `node_modules` is the exercises step will be empty

**Comment by kentcdodds** [comment]
Hmm... Interesting idea. I'm not certain I like that. I'm going to have to think about this a bit more. I think for now I'll just make sure none of the exercise steps have anything in `node_modules` by avoiding conflicting versions.
