### ISSUE TITLE
Restore scroll position of instructions on refresh

### ISSUE THREAD

**Issue by kentcdodds** [epicweb-dev/kcdshop#85]
Because this is really annoying:

https://github.com/epicweb-dev/kcdshop/assets/1500684/b929e12d-c93f-4c3e-83c6-e644eafe40f3

I think we may need to do something similar to ScrollRestoration for our own element: https://github.com/remix-run/remix/blob/main/packages/remix-react/scroll-restoration.tsx

**Comment by kentcdodds** [comment]
#87 solved the issue for when I change the README, but I'd like to find a way to solve this for when I manually refresh the page as well.

**Comment by kentcdodds** [comment]
I think the changes in #87 made it so the scrollable area stays scrolled to the bottom when you hit next:

https://github.com/epicweb-dev/kcdshop/assets/1500684/3aa5a607-085c-4884-9c02-57cdca3adf14

**Comment by onemen** [comment]
i will check it tomorrow

**Comment by onemen** [comment]
it look like when we manually set instructions.scrollTop to a value stay when we navigate, maybe we need to use `useLayoutEffect` or `useEffect`, we need to keep normal browser behavior, when going back to a page we visit the browser remember the scroll position

**Comment by onemen** [comment]
let me know what you prefer:
- always scroll back to the top when prev/next step button clicked
- restore "saved" scroll position if that step was visited before, scroll to top if not

the first option is much simple obviously

**Comment by kentcdodds** [comment]
I think I'd prefer that this works the same way the browser works. When hitting the back button, we should restore the scroll position, but when navigating we should scroll to the top.

I wonder if we could use `<Link />` `state` to store the scroll position and then have a `useEffect` with a dependency on `state` from `useLocation` that checks the state and restores the scroll position. https://reactrouter.com/en/main/components/link#state

**Comment by kentcdodds** [comment]
Fixed it!

**Comment by kentcdodds** [comment]
https://github.com/epicweb-dev/kcdshop/commit/bd0267b0f3f3854fb9a94ce6b38a44e3a0880131

**Comment by onemen** [comment]
nice. You bit me to it 👍

**Comment by kentcdodds** [comment]
This one was particularly fun. Sorry 😅

**Comment by onemen** [comment]
I've tested the kcdshop with the new commit, instructions page always scroll to the top (0) event when going back to README page i have visited before.

**Comment by kentcdodds** [comment]
It will only restore scroll when you refresh or use the browser back and forward buttons. If you navigate it moves it to the top.

**Comment by onemen** [comment]
if you interesting to apply the same for the bottom prev/next buttons I can work on it

**Comment by kentcdodds** [comment]
No, this was an intentional decision. Thanks though!
