### ISSUE TITLE
Add a link to open the README.mdx file in the editor

### ISSUE THREAD

**Issue by kentcdodds** [epicweb-dev/kcdshop#90]
I often find myself wishing I had an easy way to open the instructions I'm reading to fix a typo. Especially early on in the workshops, people will also quickly identify typos and things that need improvement and wish to make PRs and improvements. The problem with that is they're often working off their `main` branch and making PRs using the `main` branch can be problematic (I can't edit their PRs for them).

So we've got two needs here:

1. An easy way for me to launch the README.mdx in the editor
2. An easy way for workshoppers to open the README.mdx in the GitHub online editor

I'm not sure of the best way to do this. Maybe a bit at the bottom of the README that says: "Edit instructions: `<locally-icon>` `<online-icon>`"

Or maybe it's just a link and by default it opens online, but if you're holding down "alt" it switches to the local icon and opens it locally. I think I like that best.

**Comment by onemen** [comment]
![edit](https://github.com/epicweb-dev/kcdshop/assets/3650909/cc32b477-53fd-429a-b15f-dc4f60ba392b)
both links to Github page with the message `You need to fork this repository to propose changes`
[Remix](https://github.com/remix-run/remix/edit/main/docs/pages/v2.md)
[Tailwind](https://github.com/tailwindlabs/tailwindcss.com/edit/master/src/pages/docs/will-change.mdx)

Is that what you want?
Regarding `<locally-icon>` it should only be visible on development

**Comment by kentcdodds** [comment]
Let's go with the tailwind approach. I think it's more clear.

> Regarding `<locally-icon>` it should only be visible on development

I'd rather not do it this way because I want to be able to do this when developing the workshops which is a "production" setting. I think the "alt" key is a fine solution. I actually do this on my blog: https://github.com/kentcdodds/kentcdodds.com/blob/7e182a37773f49a88db5aaf14f648e8448461223/app/components/team-stats.tsx#L159-L170


https://github.com/epicweb-dev/kcdshop/assets/1500684/1df615b9-8dbd-4a48-b472-21866f81764f

Nobody really knows about this feature and it's fine with me. In our case I don't really want people to use this feature except for me anyway.
