### ISSUE TITLE
Fix home button on /finished

### ISSUE THREAD

**Issue by kentcdodds** [epicweb-dev/kcdshop#92]
The home button looks funny:

<img width="180" alt="image" src="https://github.com/epicweb-dev/kcdshop/assets/1500684/0e431cb8-09b6-4e13-9108-1729f9882988">

![image](https://github.com/epicweb-dev/kcdshop/assets/1500684/81f51fbb-7288-4fbb-b0e8-692f9816407c)

Especially when you hover:

<img width="237" alt="image" src="https://github.com/epicweb-dev/kcdshop/assets/1500684/a59dafc3-8411-4d2d-bd30-0ae318439e2d">

<img width="249" alt="image" src="https://github.com/epicweb-dev/kcdshop/assets/1500684/3d1a7ac2-6b0a-4fe9-8ccd-d7e795e7fe72">

I don't care what it looks like, but it should look nicer.

**Comment by onemen** [comment]
try if this look good to you

```diff
-  <div className="border-border flex h-16 justify-end border-t">
+  <div className="border-border flex h-16 items-center justify-end border-t">
    <ButtonLink varient="primary" prefetch="intent" to="/">
      Home
    </ButtonLink>
  </div>
```
