### ISSUE TITLE
CodeFile buttons

### ISSUE THREAD

**Issue by onemen** [epicweb-dev/kcdshop#94]
Is that what you want it to look like when all the buttons are visible? 

![buttons-new](https://github.com/epicweb-dev/kcdshop/assets/3650909/13eba32e-72de-4d46-ba60-93c4cff5abc2)

**Comment by kentcdodds** [comment]
Definitely not. My intent was that they're all in the same absolute container and spaced that way. Because the way it was before had the other buttons spaced too far from the copy button.

**Comment by onemen** [comment]
i will try to work on it.

i think i will change how it show `COPIED` near `COPY` and instead replace `COPY` with `COPIED` for 1500ms
other option is to show it below `COPY`

let me know what you prefer ?

**Comment by kentcdodds** [comment]
I'm not sure I understand the complication. I prefer the copy button to just say "COPY" and when you click it, it should change to "COPIED" for 1500ms.
