### ISSUE TITLE
add real app to examples

### ISSUE THREAD

**Issue by onemen** [epicweb-dev/kcdshop#96]
If you add 'real' app, one form `full-stack-foundations` 07, It can help with testing and debugging

**Comment by kentcdodds** [comment]
Yeah, I think the example directory could be improved. In some ways it has too much, in others it has too little.

**Comment by kentcdodds** [comment]
Here's what I do:

```
KCDSHOP_CONTEXT_CWD=/Users/kentcdodds/code/epicweb-dev/data-modeling npm run dev
```

This works pretty well whenever I want to test it actually running as expected.
