### ISSUE TITLE
Fix narrow screen issues

### ISSUE THREAD

**Issue by kentcdodds** [epicweb-dev/kcdshop#99]
I'm not sure why, but the tabs aren't showing up:

<img width="910" alt="image" src="https://github.com/epicweb-dev/kcdshop/assets/1500684/1e9f472f-5004-44c4-8d96-d7f4d779ecbe">

**Comment by onemen** [comment]
I only manage to reproduce it one time, then it run away and hide...

there is also an issue with the apps drop-down list it is cut at the top

![apps](https://github.com/epicweb-dev/kcdshop/assets/3650909/a11d5e4a-b282-49fd-97b2-ab4038b83d84)

**Comment by onemen** [comment]
@kentcdodds 

`<Tabs.List className="scrollbar-thin scrollbar-thumb-scrollbar mb-[-8px] inline-flex h-14 overflow-x-scroll">`

I don't know why but adding min-height help, try to add `min-h-14`

**Comment by onemen** [comment]
there are multiple scrollbars on diff view
